/*
 * file: test.c
 * description: .so module to test the server
 * author: Lewis Cheng
 * date: 2011.09.14
 */

#include "uhttpd.h"

ssize_t handler(char *buf, arg_list_type list) {
	xstrcpy(buf, 
		"<html>\r\n"
		"\t<body>\r\n"
		"\t\t<h1>Test Page</h1>\r\n"
		"\t\t<p>This page is generated by test.so.</p>\r\n"
		"\t\t<hr>\r\n",
		MAX_INTERNAL_HTML_SIZE);
	arg_node_type *curr = list->link;
	while (curr != NULL) {
		strcat(buf, "\t\t<p>Key=");
		strcat(buf, curr->key);
		strcat(buf, ", value=");
		strcat(buf, curr->value);
		strcat(buf, "</p>\r\n");
		curr = curr->link;
	}
	strcat(buf, "\t</body>\r\n""</html>\r\n");
	return xstrlen(buf, MAX_INTERNAL_HTML_SIZE);
}
